import Colors from '../Assets/Colors';

const DATA = [
  {
    title: 'Upcoming',
    tag: 'View cricket schedule upcoming',
    button: 'Watch',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.RED,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Play and Win',
    tag: 'Live Cricket TV',
    button: 'Join',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.VIOLET,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Recent',
    tag: 'All recent cricket matches',
    button: 'Know',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.ORANGE,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Venue',
    tag: 'Total Venue and ground details',
    button: 'Search',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.LT_BLUE,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Football',
    tag: 'View cricket schedule upcoming',
    button: 'Highlights',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.LT_GREEN,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Basketball',
    tag: 'View cricket schedule upcoming',
    button: 'Score',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.RED,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'Tennis',
    tag: 'View cricket schedule upcoming',
    button: 'Watch',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.VIOLET,
    isActive: false,
    head: 'Live',
  },
  {
    title: 'About Us',
    tag: 'View cricket schedule upcoming',
    button: 'Know More',
    imagepath: require('../Assets/Images/Shape.png'),
    bcolor: Colors.LT_BLUE,
    isActive: false,
    head: 'Live',
  },
];
export default DATA;
