import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'F7F7FA',
    justifyContent: 'space-evenly',
  },
  topView: {
    marginBottom: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  textView1: {
    width: 80,
    height: 80,
    textAlign: 'center',
    paddingVertical: 25,
    fontSize: 20,
    borderRadius: 30,
    color: 'white',
  },
  middleView: {
    marginBottom: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  textView2: {
    width: 80,
    height: 80,

    textAlign: 'center',
    paddingVertical: 25,
    fontSize: 20,
    color: 'white',
    borderRadius: 30,
  },
  textView3: {
    width: 80,
    height: 80,

    textAlign: 'center',
    paddingVertical: 25,
    fontSize: 20,
    color: 'white',
    borderRadius: 30,
  },
  textView4: {
    width: 80,
    height: 80,
    textAlign: 'center',
    paddingVertical: 25,
    fontSize: 20,
    color: 'white',
    borderRadius: 30,
  },
  inputAndroid: {
    marginVertical: 10,
    borderRadius: 10,
    marginHorizontal: 10,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: '#373B61',
  },
  inputIOS: {
    marginVertical: 10,
    borderRadius: 10,
    height: 50,
    marginHorizontal: 10,
    backgroundColor: '#EDEFFE',
    elevation: 6,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: '#373B61',
  },
  btn_view: {
    width: '60%',
    alignSelf: 'center',
    marginTop: 50,
    marginHorizontal: 15,
    flexDirection: 'column',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00E0C6',
    height: 50,
    borderRadius: 30,
    elevation: 6,
    padding: 10,
  },
  text_inside_btn: {
    color: '#252525',
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  btn_view: {
    width: '60%',
    alignSelf: 'center',
    marginTop: 50,
    marginHorizontal: 15,
    flexDirection: 'column',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00E0C6',
    height: 50,
    borderRadius: 30,
    elevation: 6,
    padding: 10,
  },
  text_inside_btn: {
    color: '#252525',
    alignSelf: 'center',
    fontWeight: 'bold',
  },
});
export default styles;
